/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: JUSTGAME (https://sketchfab.com/JUSTGAME)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/koenigsegg-gemera-c174dde53a9e40a291475e07db426dc9
Title: Koenigsegg Gemera
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Car(props) {
  const { nodes, materials } = useGLTF("/koenigsegg_gemera.glb");

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ColouredMtl-material"].geometry}
          material={materials.ColouredMtl}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ColouredMtl-material_1"].geometry}
          material={materials.ColouredMtl}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_1"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_1"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_2"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_3"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Base-material"].geometry}
          material={materials.CSR2_Base}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Carbon1-material"].geometry}
          material={materials.CSR2_Carbon1}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Carbon1M-material"].geometry}
          material={materials.CSR2_Carbon1M}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["GlassClear-material"].geometry}
          material={materials.GlassClear}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__1-material"].geometry}
          material={materials.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Grille3-material"].geometry}
          material={materials.CSR2_Grille3}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_4"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_5"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Interior-material"].geometry}
          material={materials.CSR2_Interior}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_6"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_InteriorA-material"].geometry}
          material={materials.CSR2_InteriorA}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_7"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_InteriorTillingColourZone-material"].geometry}
          material={materials.CSR2_InteriorTillingColourZone}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_InteriorTillingColourZone-material_1"].geometry}
          material={materials.CSR2_InteriorTillingColourZone}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_CarPaint-material"].geometry}
          material={materials.CSR2_CarPaint}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_2"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_1"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_2"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_3"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_4"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Base-material_1"].geometry}
          material={materials.CSR2_Base}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Carbon1-material_1"].geometry}
          material={materials.CSR2_Carbon1}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Carbon1M-material_1"].geometry}
          material={materials.CSR2_Carbon1M}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_5"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["GlassClear-material_1"].geometry}
          material={materials.GlassClear}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__1-material_1"].geometry}
          material={materials.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Grille3-material_1"].geometry}
          material={materials.CSR2_Grille3}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_8"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_9"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Interior-material_1"].geometry}
          material={materials.CSR2_Interior}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_10"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_InteriorTillingColourZone-material_2"].geometry}
          material={materials.CSR2_InteriorTillingColourZone}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_InteriorA-material_1"].geometry}
          material={materials.CSR2_InteriorA}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_InteriorTillingColourZone-material_3"].geometry}
          material={materials.CSR2_InteriorTillingColourZone}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_CarPaint-material_1"].geometry}
          material={materials.CSR2_CarPaint}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_3"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_6"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_7"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_8"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_9"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["clear-material"].geometry}
          material={materials.clear}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["EXT_WHEEL-material"].geometry}
          material={materials.EXT_WHEEL}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["EXT_WHEEL-material_1"].geometry}
          material={materials.EXT_WHEEL}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["EXT_WHEEL-material_2"].geometry}
          material={materials.EXT_WHEEL}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["EXT_WHEEL-material_3"].geometry}
          material={materials.EXT_WHEEL}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__1-material_2"].geometry}
          material={materials.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__1-material_3"].geometry}
          material={materials.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__1-material_4"].geometry}
          material={materials.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["GlassRed-material"].geometry}
          material={materials.GlassRed}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Grille1-material"].geometry}
          material={materials.CSR2_Grille1}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Grille2-material"].geometry}
          material={materials.CSR2_Grille2}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Light-material"].geometry}
          material={materials.CSR2_Light}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Light-material_1"].geometry}
          material={materials.CSR2_Light}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Light-material_2"].geometry}
          material={materials.CSR2_Light}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Badge-2-material"].geometry}
          material={materials["CSR2_Badge-2"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Base-material_2"].geometry}
          material={materials.CSR2_Base}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_11"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Carbon1M-material_2"].geometry}
          material={materials.CSR2_Carbon1M}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_12"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__1-material_5"].geometry}
          material={materials.material}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_10"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Carbon1-material_2"].geometry}
          material={materials.CSR2_Carbon1}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_11"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Light-material_3"].geometry}
          material={materials.CSR2_Light}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_12"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_13"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_13"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_14"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_14"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_15"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_4"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_16"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_17"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_18"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Interior-material_2"].geometry}
          material={materials.CSR2_Interior}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_InteriorTillingColourZone-material_4"].geometry}
          material={materials.CSR2_InteriorTillingColourZone}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_19"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Light-material_4"].geometry}
          material={materials.CSR2_Light}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Mirrors-material"].geometry}
          material={materials.Mirrors}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-2-material"].geometry}
          material={materials["CSR2_Coloured-2"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["Mirrors-material_1"].geometry}
          material={materials.Mirrors}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ColouredMtl-material_2"].geometry}
          material={materials.ColouredMtl}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_5"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["ColouredMtl-material_3"].geometry}
          material={materials.ColouredMtl}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_6"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_7"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Badge-2-material_1"].geometry}
          material={materials["CSR2_Badge-2"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_20"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_CarPaint-material_2"].geometry}
          material={materials.CSR2_CarPaint}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_21"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_22"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-2-material_1"].geometry}
          material={materials["CSR2_Coloured-2"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["clear-material_1"].geometry}
          material={materials.clear}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["chrome-material"].geometry}
          material={materials.chrome}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Carbon1M-material_3"].geometry}
          material={materials.CSR2_Carbon1M}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_15"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_23"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_24"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_InteriorTillingColourZone-material_5"].geometry}
          material={materials.CSR2_InteriorTillingColourZone}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__002-material_25"].geometry}
          material={materials["0.002"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Badge-material"].geometry}
          material={materials.CSR2_Badge}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Carbon1M-material_4"].geometry}
          material={materials.CSR2_Carbon1M}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_16"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Grille1-material_1"].geometry}
          material={materials.CSR2_Grille1}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_17"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Coloured-material_18"].geometry}
          material={materials.CSR2_Coloured}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_CarPaint-material_3"].geometry}
          material={materials.CSR2_CarPaint}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rim_carbon-material"].geometry}
          material={materials.rim_carbon}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rim-material"].geometry}
          material={materials.CSR2_Wheel1C_Rim}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rim-material_1"].geometry}
          material={materials.CSR2_Wheel1C_Rim}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_8"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rotor-material"].geometry}
          material={materials.CSR2_Wheel1C_Rotor}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rim_carbon-material_1"].geometry}
          material={materials.rim_carbon}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rim-material_2"].geometry}
          material={materials.CSR2_Wheel1C_Rim}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rim-material_3"].geometry}
          material={materials.CSR2_Wheel1C_Rim}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_9"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rotor-material_1"].geometry}
          material={materials.CSR2_Wheel1C_Rotor}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rim_carbon-material_2"].geometry}
          material={materials.rim_carbon}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rim-material_4"].geometry}
          material={materials.CSR2_Wheel1C_Rim}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rim-material_5"].geometry}
          material={materials.CSR2_Wheel1C_Rim}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_10"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rotor-material_2"].geometry}
          material={materials.CSR2_Wheel1C_Rotor}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["rim_carbon-material_3"].geometry}
          material={materials.rim_carbon}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rim-material_6"].geometry}
          material={materials.CSR2_Wheel1C_Rim}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rim-material_7"].geometry}
          material={materials.CSR2_Wheel1C_Rim}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["__003-material_11"].geometry}
          material={materials["0.003"]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["CSR2_Wheel1C_Rotor-material_3"].geometry}
          material={materials.CSR2_Wheel1C_Rotor}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/koenigsegg_gemera.glb");
