import React from "react";
import { useGLTF } from "@react-three/drei";

export function Hotel(props) {
  const { nodes, materials } = useGLTF("/for_pashapashas_diner.glb");
  return (
    <group  {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2.geometry}
          material={materials.material_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_1.geometry}
          material={materials.material_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_2.geometry}
          material={materials.material_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_3.geometry}
          material={materials.auto}
        />
        <lineSegments
          geometry={nodes.Material4.geometry}
          material={materials.edge_color646464255}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3.geometry}
          material={materials.auto_1}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_1.geometry}
          material={materials.auto_2}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_2.geometry}
          material={materials.auto_5}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_3.geometry}
          material={materials.auto_6}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_4.geometry}
          material={materials.auto_7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_5.geometry}
          material={materials.auto_8}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_6.geometry}
          material={materials.auto_12}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_7.geometry}
          material={materials.auto_13}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_8.geometry}
          material={materials.auto_14}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_9.geometry}
          material={materials.auto_15}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_10.geometry}
          material={materials.auto_16}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_11.geometry}
          material={materials.auto_17}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_12.geometry}
          material={materials.auto_18}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_13.geometry}
          material={materials.auto_20}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_14.geometry}
          material={materials.auto_21}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_15.geometry}
          material={materials.auto_25}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_16.geometry}
          material={materials.auto_26}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_17.geometry}
          material={materials.auto_29}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_18.geometry}
          material={materials.auto_32}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_19.geometry}
          material={materials.auto_31}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_20.geometry}
          material={materials.auto_34}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_21.geometry}
          material={materials.auto_35}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_22.geometry}
          material={materials.auto_39}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_23.geometry}
          material={materials.auto_50}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_24.geometry}
          material={materials.auto_51}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_25.geometry}
          material={materials.auto_52}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_26.geometry}
          material={materials.auto_53}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_27.geometry}
          material={materials.auto_57}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_28.geometry}
          material={materials.auto_59}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_29.geometry}
          material={materials.auto_62}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_4.geometry}
          material={materials.auto_66}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_30.geometry}
          material={materials.auto_65}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_31.geometry}
          material={materials.auto_67}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_32.geometry}
          material={materials.auto_68}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_33.geometry}
          material={materials.auto_79}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_34.geometry}
          material={materials.auto_81}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_35.geometry}
          material={materials.auto_82}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_5.geometry}
          material={materials.auto_90}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_6.geometry}
          material={materials.auto_93}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_36.geometry}
          material={materials.auto_95}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_37.geometry}
          material={materials.auto_102}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_7.geometry}
          material={materials.auto_104}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_38.geometry}
          material={materials.auto_116}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_39.geometry}
          material={materials.auto_123}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_40.geometry}
          material={materials.auto_124}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_41.geometry}
          material={materials.auto_135}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_42.geometry}
          material={materials.auto_137}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_43.geometry}
          material={materials.auto_163}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_8.geometry}
          material={materials.auto_171}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_44.geometry}
          material={materials.auto_178}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material2_9.geometry}
          material={materials.auto_181}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Material3_45.geometry}
          material={materials.auto_190}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/for_pashapashas_diner.glb");
